# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5b85f0b5db8b50030fd8b730c9a38f1897489de3ea5f68d5fd30692c81207b97cc7cdd89dbb42b9d5bbe365d1e33372810481409263c940c65cebffd4d6de04

test:
  secret_key_base: 334f9d18498591159ded0a4cdca58c7512709837eec893da006682a2482875596410d0ad75fdfaa09f6a46d4a62056089c788466eb0bcc7aef0b6ac6e885e34e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
